name: Manual Run

on:
  workflow_dispatch:
    inputs:
      reason:
        description: Reason for running this workflow
        required: false
        default: Manual trigger

jobs:
  echo:
    name: Echo context
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Print run context
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Ref: $GITHUB_REF"
          echo "Actor: $GITHUB_ACTOR"
          echo "Reason: ${{ github.event.inputs.reason }}"
          date
